# Generated by Django 4.2.3 on 2023-07-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
